### ISSUE TITLE
🔧 Add env variable for log level

### ISSUE THREAD

**Issue by jbleduigou** [jbleduigou/budgetcategorizer#258]
Currently the log level is hard coded to `DEBUG`.  
We should add a new env variable for this.

**Comment by jbleduigou** [comment]
Changes to be made are in:  
* `main.go` function `initLogger`
* `template.yaml`

**Comment by Sarath2991** [comment]
Hi @jbleduigou, 

I would like to contribute for this issue. My approach would be to add one more parameter for Loglevel in the CloudFormation Template(template.yaml) and based on the input of the env variable in main.go an internal function can return the zapcore loglevel for the initlogger.

Please let me know if you would like my contribution.

**Comment by jbleduigou** [comment]
Hi @Sarath2991,  
Thanks for looking at this issue!  
That is the approach I was thinking of.  
I woul be glad to see you contribute.

**Comment by Sarath2991** [comment]
Hi @jbleduigou, 

Will you be creating a branch for me to start the work and raise the PR?

**Comment by jbleduigou** [comment]
Hi @Sarath2991, usually people fork the repo then make the code changes and eventually submit a pull request.  
See this page for more info: https://jarv.is/notes/how-to-pull-request-fork-github/

**Comment by jbleduigou** [comment]
Fixed by https://github.com/jbleduigou/budgetcategorizer/pull/262
