### ISSUE TITLE
Do not assign a default category when parsing 

### ISSUE THREAD

**Issue by jbleduigou** [jbleduigou/budgetcategorizer#3]
I was looking at the tests in parser_test.go
It is surprising to see that some transactions get assigned the category _Courses Alimentation_ by default.

Fix consists of :
1. Update parser_test.go by replacing "Courses Alimentation" by ""
2. Modify parser.go so that tests are passing and no category is assigned by default

**Comment by cassioesp** [comment]
Hi @jbleduigou! I took a look at parser.go and remove Courses Alimentation as default category for debit transactions and opened the PR #123 . Is that correct? Thanks in advance!

**Comment by jbleduigou** [comment]
Thanks Cássio for contributing!
